var rule = {
  title: '水晶影院',
  host: 'https://www.xxza.top/',
  url: '/fyclass.html',
  searchUrl: '/search.html?wd=**',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  filter: '',
  filter_url: '',
  filter_def: {},
  headers: {
    'User-Agent': 'PC_UA',
  },
  timeout: 5000,
  class_parse: '.navbar-left li;a&&Text;a&&href;/(?<=\/\/www\.xxza\.top\/)([^/]+)(?=\.html$)',
  cate_exclude: '明星|节目|榜单|最新|网站地图',
  play_parse: true,
  lazy: "js:\n  input = { parse: 1, url: input, js: '' };",
  double: true,
  推荐: 'body .col-md-8;li;a&&title;a&&data-original;.score&&Text;a&&href;.text-bg-r&&Text',
  一级: 'body .col-sm-3;a&&title;a&&data-original;.text-bg-c&&Text;a&&href;.text-muted&&Text',
  二级: {
    title: 'h1&&Text',
    img: 'a.video-pic&&style',
    desc: '主要信息;年代;地区;演员;导演',
    content: '.details-content-all&&Text',
    tabs: 'ul.nav-tabs:eq(0)',
    lists: '.playlist&&ul&&li',
    tab_text: 'body&&Text',
    list_text: 'body&&Text',
    list_url: 'a&&href',
  },
  搜索: '.col-md-2;a&&title;a&&data-original;;a&&href',
}